<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.lessons</groupId>
  <artifactId>angularApp16</artifactId>
  <version>1.0-SNAPSHOT</version>



  <name>angularApp16</name>

  <packaging>pom</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <!-- Tell Maven to compile for Java 17 -->
    <maven.compiler.release>17</maven.compiler.release>
    <maven.compiler.verbose>false</maven.compiler.verbose>

    <!-- Specify where the URI for the Amazon Container Registry -->
    <aws.ecr.uri>524647912468.dkr.ecr.us-east-1.amazonaws.com/apps/app16</aws.ecr.uri>

    <!-- Specify the AWS environment name -->
    <aws.env.name>dev</aws.env.name>
  </properties>


  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>17</source>
          <target>17</target>
        </configuration>
      </plugin>
    </plugins>
  </build>


  <profiles>

    <!--    B U I L D     I M A G E      P R O F I L E      (for running this app in a container)  -->
    <profile>
      <id>buildImage</id>

      <modules>
        <module>common-backend</module>
        <module>backend</module>
        <module>frontend</module>
      </modules>
    </profile>


    <!--    B U I L D     I M A G E    A N D    P U S H       W E B A P P    (for running this app in a container)  -->
    <profile>
     <id>buildAndPushImage</id>

      <modules>
        <module>common-backend</module>
        <module>backend</module>
        <module>frontend</module>
      </modules>
    </profile>


    <!--    B U I L D     I M A G E    A N D    P U S H       S Y N C    S E R V I C E    (for running this app in a container)  -->
    <profile>
      <id>buildAndPushSyncService</id>

      <modules>
        <module>db-migrations</module>
        <module>common-backend</module>
        <module>sync-service</module>
      </modules>
    </profile>



    <!--    D E F A U L T        P R O F I L E           (for developers)  -->
    <profile>
      <id>default</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>

      <modules>
        <module>frontend</module>
        <module>backend</module>
        <module>db-migrations</module>
        <module>sync-service</module>
        <module>common-backend</module>
      </modules>

    </profile>

  </profiles>


</project>