###############################################################################
# application.yaml   (used when running in a container)
###############################################################################

# Set the Active profile to be dev
spring.profiles.active: prod

# Tell spring not to run flyway on start-up
spring.flyway.enabled: false



##########################################################
# Run Settings
#########################################################
# If true,  then this runs as a service  (so it refreshes on startup and every night)
# If false, then this runs once and then stops
run.service_mode: false

# If true, then a sync process will be performed on startup
run.sync_on_startup: true



##########################################################
# Database Settings
##########################################################
app.datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    schema: ${POSTGRES_SCHEMA_NAME}
    maxPoolSize: ${POSTGRES_POOL_SIZE:20}
    database-name: ${POSTGRES_DB_NAME}
    flyway-migrate-on-startup: true



###########################################################
# ElasticSearch Settings
##########################################################
es:
    url: ${ES_URL}
    ssl_enabled: true
    key-store: ${INCOMING_KEYSTORE_FILEPATH}
    key-store-password:  ${INCOMING_KEYSTORE_PASSWORD}
    key-store-type: JKS
    trust-store:  ${INCOMING_TRUSTSTORE_FILEPATH}
    trust-store-password: ${INCOMING_TRUSTSTORE_PASSWORD}
    trust-store-type: JKS
    authentication.principal: ${ES_USERNAME}
    authentication.password:  ${ES_PASSWORD}



##############################################################################
# Email Settings
#
# If email.mode==off,  then the emails are not sent out but are logged
# If email.mode==demo, then the emails are sent only to the email.demo.recipient_email
# If email.mode==prod, then the emails are sent out to the assigned userid
#
# NOTE:  The EmailService will extract the hostname from the email.smtp.host.url
##############################################################################
email.mode:      'off'                           # possible modes are off, demo, and prod


##########################################################
# Document Settings
##########################################################
s3.enabled: false