##############################################################################
# Settings for the "local_oauth2" profile
##############################################################################
name: app16
server.servlet.context-path: /app16

# Provide the trustStore for the local keycloak


# Disable cors check because we are running in local dev mode
# NOTE:  order is important.  Make sure disable.cors comes *AFTER* you set the profile
disable.cors: true


# Show Exception info to local developers
exception_handler.return_dev_info: true


# Disable setting the last_login_date upon authentication
# NOTE:  When running in local mode, there is no saved session.  So, every REST call runs sql to update the user's last login date
#        Setting this flag to false ensures that the last login date is NOT set (which reduces the load on the developer's laptop)
authenticate.set_last_login_date.is_enabled: false



##########################################################
# Security & SSL Settings
#
# Set the security mode to "keycloak" so it authenticates against keycloak
##########################################################
security.mode: keycloak          # Possible values are localdev or keycloak

server:
  port: 8443
  ssl:
    key-store: backend/src/main/dev-resources/webapp.keystore.jks
    key-store-password: changeit
    key-store-type: JKS
    trust-store: backend/src/main/dev-resources/webapp.truststore.jks
    trust-store-password: changeit
    trust-store-type: JKS
    enabled: true

# Secure the cookies
server.servlet.session.cookie.secure: true
server.servlet.session.cookie.http-only: true

server.use-forward-headers: true


##############################################################################
# Keycloak Settings for Spring Security
#
# The realm url is probably something like https://keycloak.rbr-tech.com:8444/realms/MyRealm
##############################################################################
spring.security.oauth2.client.registration.keycloak.client-id: app16-webapp
spring.security.oauth2.client.registration.keycloak.client-secret: QpmSS6gSkmWfJzG0al6Ycor24OtSgsDK
spring.security.oauth2.client.registration.keycloak.authorization-grant-type: authorization_code
spring.security.oauth2.client.registration.keycloak.scope: openid,email,profile,phone,address
spring.security.oauth2.client.provider.keycloak.issuer-uri: https://localhost.localdomain2:8444/realms/MyRealm
spring.security.oauth2.client.provider.keycloak.user-name-attribute: preferred_username



##########################################################
# Database Settings
##########################################################
app.datasource:
  enabled: true
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/app16_db
  username: app16_user
  password: secret
  schema: app16_db
  maxPoolSize: 2
  database-name: app16_db




##########################################################
# ElasticSearch Settings
##########################################################
es:
  url: http://localhost:9201
  ssl_enabled: false


